### ISSUE TITLE
App iOS name should be "SmartDeco", with SmartDeco icon

### ISSUE THREAD

**Issue by tedbarnett** [SmartDecoLLC/pumpkin#1]
For demo purposes, can we make sure that the app looks like the real "SmartDeco" app?  That would mean:

1. App name (in iOS UI) is "SmartDeco"
2. App icon is based on the attached image (two versions)

White background:

![SmartDeco_logo_small_white_background 500x500](https://user-images.githubusercontent.com/694013/97819538-1e4d4b00-1c77-11eb-88b1-6f8fddc42347.png)

Transparent background: 
![SmartDeco_logo_small_transparent 500x500](https://user-images.githubusercontent.com/694013/97819540-1ee5e180-1c77-11eb-9552-e0bb840659f1.png)

**Comment by oliviabarnett** [comment]
Added images & changed name
